### ISSUE TITLE
Add PropertyMock support

### ISSUE THREAD

**Issue by nvgoldin** [pksol/mock_autogen#1]
Currently the useful error message is displayed:
```python
E           TypeError: Unsupported mocking object: <class 'mock.mock.PropertyMock'>. You are welcome to add code to support it :)
```

**Comment by pksol** [comment]
Some links about usage:
https://docs.python.org/3/library/unittest.mock.html#unittest.mock.PropertyMock
https://stackoverflow.com/questions/42704506/how-to-mock-a-property
