### ISSUE TITLE
Feature : discover what to mock based on unit under test

### ISSUE THREAD

**Issue by terroirman** [pksol/mock_autogen#20]
Unless I'm mistaking, the only way to use the library is to tell it what to mock (module, class, method).

It would be nice if we could specify the unit under test (ex.: a method) and then mock_autogen would discover what to mock, based on what's in there.

If we take your example in the doc, it would be nice if we could call it like : 

```
from os_wrapper import os_remove_wrap
from mock_autogen.pytest_mocker import PytestMockerUUT

generated_mocks = PytestMockerUUT(os_remove_wrap).mock_everything().generate() 
```

The result would be 
```
print(generated_mocks)
mock_remove = mocker.MagicMock(name='remove')
mocker.patch('os.remove', new=mock_remove)
```

**Comment by pksol** [comment]
Interesting!

Were you thinking about some sort of [AST parsing](https://docs.python.org/3/library/ast.html) of the UUT?

For functions - I can imagine looking for [calling function instructions](https://docs.python.org/3/library/ast.html#ast.Call) which can be extracted and mocked.

What about entire modules, classes, or instances sent as UUT? What to extract from there?

**Comment by terroirman** [comment]
Thanks for your interest! I'm quite ignorant on how it would be implemented... I had a quick look at AST parsing (and the calling function instructions) and that seems pretty much to the idea I have.

As for module, classes, instances... I'm pretty new to python unit tests, so its quite hard to even know what I'd want lol! Ie.: maybe it would make sense, maybe not, but I'm not quite sure.

At first glance, I think it wouldn't make sense to send something other than a function.

The way I see it, with the current version of this library the process is : 
1. Identify function you want to test
2. Identify dependencies you want to mock
3. Call PytestMocker against those found on step 2
4. Use the generated mocks/asserts in your unit test

My idea was : there must be a way to automate step 2 and 3 (given 1). 
Another idea: what about wrapping the generate function call in eval() ? Would it makes sense ? security issue ?

**Comment by pksol** [comment]
Makes sense to start with sending a function. Can always add support for classes and modules if that would make sense later.

Regarding the usage of eval - I do use it in the tests to verify the output of the library but I'm not sure it should be an automated part of the library: people often have to modify the output, so an eval might break their tests.

**Comment by pksol** [comment]
I began to explore this idea - looks like it is very possible to cover 80% of cases.

**Comment by kvshravan** [comment]
@pksol https://stackoverflow.com/questions/57582448/using-sqlalchemy-and-with-magicmock The answer that you've given for this question , I don't really get it , could you please be more elaborate? I'm working on something where I wanna mock this query: 
TestResultFile.query.filter(and_(conditions)).order_by().limit().all() , I thought you'd be the one helpful , can't find any other socials , so needed to contact here.

**Comment by pksol** [comment]
Hi @terroirman,
I know it took some time, but I used your advice to extend the functionality and also simplify the API.

If your function under test is called `os_remove_wrap`, you can generate mocks using a simple command: 

`mock_autogen.generate_uut_mocks(os_remove_wrap)`

This function outputs the generated mocks to the console and copies it to the clipboard, so a simple ctrl+V is enough! No need to wrap it in `print` anymore.

I updated the version of the library to 2.0.1, since it's a major API change.

Done in #21. More info can be found in the [README](https://github.com/pksol/mock_autogen#readme).

**Comment by terroirman** [comment]
Hey thanks for your work. That seems promising ! I'll give it a try shortly.
