### ISSUE TITLE
Output of uut mocks not show as per example

### ISSUE THREAD

**Issue by jmeachum** [pksol/mock_autogen#26]
First of thanks for developing such a useful tool. I wanted to provide some feedback on the documentation from the perspective a new user. I followed the example from the documentation, but one gap I found is I was not getting the output from pytest. I found that I needed to run pytest with the -rP or -rx flag, depending on status of the test (pass vs fail) to see the output. I realize this isn't an issue with the module but rather the way pytest outputs stdout for tests. I thought it would be useful to include this into the documentation for future users.

Cheers

**Comment by pksol** [comment]
Thanks @jmeachum, I love hearing feedback from users and knowing that this library helps others!

It's probably a good idea to add a "Troubleshooting" section to the documentation.
