### ISSUE TITLE
Pyperclip does not add output to clipboard

### ISSUE THREAD

**Issue by jmeachum** [pksol/mock_autogen#27]
I receive the following error on a Linux system when I use the mock_autogen.generate_uut_mocks(function_name) function.

`
------------------------------------------------------------------------------------------------------------------------------------------------- Captured log call -------------------------------------------------------------------------------------------------------------------------------------------------
WARNING  mock_autogen.utils:utils.py:28 Could not copy func results to clipboard
Traceback (most recent call last):
  File "/home/username/Documents/code/test_mock_gen/.envtest/lib/python3.6/site-packages/mock_autogen/utils.py", line 25, in to_clipboard
    pyperclip.copy(result)
  File "/home/username/Documents/code/test_mock_gen/.envtest/lib/python3.6/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/home/username/Documents/code/test_mock_gen/.envtest/lib/python3.6/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error
`

**Comment by jmeachum** [comment]
I did find additional instructions on the paperclip link provided in the error. Not sure if adding a dependency for linux systems on the install of the package or update the doco to include this dependency would work best.

**Comment by jmeachum** [comment]
I'm also running this via bash terminal so it's possible that is another reason for it not working.

**Comment by pksol** [comment]
Installing additional low-level dependencies is something I want to avoid at this stage since every distribution has its quirks. 

Instead, this error and basic instructions can be added to the "Troubleshooting" section of the documentation.

**Comment by jmeachum** [comment]
> Installing additional low-level dependencies is something I want to avoid at this stage since every distribution has its quirks.
> 
> Instead, this error and basic instructions can be added to the "Troubleshooting" section of the documentation.

That sounds reasonable. I did find afterwards that it appears you need some type of windowing environment in unix for pyperclip to work. Or least that's what I gathered when trying to get it working and installing the various libraries it's documentation suggested. I'm not sure if there is a way to add clipboard functionality to a terminal. In my case I'm using VScode on a Windows 10 host and connect to a unix server to develop using the remote ssh extension.

**Comment by jmeachum** [comment]
So digging into this a bit more, I found this particular issue explains in detail the issue I'm having and appears to be well known with VSCode Remote SSH. When I get a working config I will post it in here. My contribution to the troubleshooting guide.
https://github.com/microsoft/vscode-remote-release/issues/4600

**Comment by pksol** [comment]
@jmeachum , would you like to review the documentation before I merge it?

https://github.com/pksol/mock_autogen/pull/36

**Comment by jmeachum** [comment]
Sorry for the late reply. I read it and it looks sufficient. On a side note I had some issues trying to get X11 forwarding working which is the root cause of my issue.

**Comment by pksol** [comment]
No problem, this documentation can help others as well.

**Comment by pksol** [comment]
Updated https://pypi.org/project/pytest-mock-generator/ documentation and usage accordingly.
